In [ ]:
from keras.models import Model
from keras.layers import Input, Dense, SimpleRNN, LSTM, TimeDistributed
import numpy as np

In [ ]:
# first data set
h, e, l, o = 0, 1, 2, 3
x = np.array([[[h], [e], [l], [l]]], dtype=np.float32)
y = np.array([[[e], [l], [l], [o]]], dtype=np.float32)

print("x:", x, x.shape)
print("y:", y, y.shape)

x: [[[0.]
  [1.]
  [2.]
  [2.]]] (1, 4, 1)
y: [[[1.]
  [2.]
  [2.]
  [3.]]] (1, 4, 1)


In [ ]:
model_type = 1 # 1: Regression, 2: Classification

In [ ]:
x_input = Input(batch_shape=(None, x.shape[1], 1))
rnn = LSTM(4, return_sequences=True)(x_input)
print(rnn)
if model_type == 1:
  x_output = TimeDistributed(Dense(1))(rnn)
  #x_output = Dense(1)(rnn)
elif model_type == 2:
  x_output = TimeDistributed(Dense(4, activation="softmax"))(rnn)
  #x_output = Dense(4, activation="softmax")(rnn)

KerasTensor(type_spec=TensorSpec(shape=(None, 4, 4), dtype=tf.float32, name=None), name='lstm_1/PartitionedCall:1', description="created by layer 'lstm_1'")


In [ ]:
model = Model(x_input, x_output)

if model_type == 1:
  model.compile(loss='mean_squared_error', optimizer='adam')
elif model_type == 2:
  model.compile(loss='sparse_categorical_crossentropy', optimizer='adam')

print(model.summary())

Model: "model_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_3 (InputLayer)         [(None, 4, 1)]            0         
_________________________________________________________________
lstm_1 (LSTM)                (None, 4, 4)              96        
_________________________________________________________________
time_distributed_2 (TimeDist (None, 4, 4)              20        
Total params: 116
Trainable params: 116
Non-trainable params: 0
_________________________________________________________________
None


In [ ]:
model.fit(x, y, epochs=1000, batch_size=1, verbose=0)

In [ ]:
pred = model.predict(x, batch_size=1)
if model_type == 1:
  print(pred)
elif model_type == 2:
  pred = np.squeeze(pred, axis=0)
  print(np.round(pred, 3))
  idx = [np.argmax(r) for r in pred]
  print(idx)

[[0.004 0.988 0.006 0.002]
 [0.    0.006 0.993 0.001]
 [0.    0.001 0.994 0.005]
 [0.    0.    0.009 0.991]]
[1, 2, 2, 3]
