In [ ]:
from keras.models import Model
from keras.layers import Input, Dense, SimpleRNN, LSTM
import numpy as np

In [ ]:
# first data set
h, e, l, o = 0, 1, 2, 3
x = np.array([[[h], [e], [l], [l]]], dtype=np.float32)
y = np.array([[o]], dtype=np.float32)

# second data set
#l, e, a, r, n, i, g = 0, 1, 2, 3, 4, 5, 6
#x = np.array([[[l], [e], [a], [r], [n], [i], [n]]], dtype=np.float32)
#y = np.array([[g]], dtype=np.float32)

print("x:", x, x.shape)
print("y:", y, y.shape)

x: [[[0.]
  [1.]
  [2.]
  [2.]]] (1, 4, 1)
y: [[3.]] (1, 1)


In [ ]:
model_type = 2 # 1: Regression, 2: Classification

In [ ]:
x_input = Input(batch_shape=(None, x.shape[1], 1))
print(x_input.shape)
rnn = SimpleRNN(4)(x_input)
if model_type == 1:
  x_output = Dense(1)(rnn)
elif model_type == 2:
  x_output = Dense(4, activation="softmax")(rnn)

(None, 4, 1)


In [ ]:
model = Model(x_input, x_output)

if model_type == 1:
  model.compile(loss='mean_squared_error', optimizer='adam')
elif model_type == 2:
  model.compile(loss='sparse_categorical_crossentropy', optimizer='adam')

print(model.summary())

Model: "model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         [(None, 4, 1)]            0         
_________________________________________________________________
simple_rnn (SimpleRNN)       (None, 4)                 24        
_________________________________________________________________
dense (Dense)                (None, 4)                 20        
Total params: 44
Trainable params: 44
Non-trainable params: 0
_________________________________________________________________
None


In [ ]:
# weights for input
model.layers[1].weights[0]

<tf.Variable 'simple_rnn/simple_rnn_cell/kernel:0' shape=(1, 4) dtype=float32, numpy=
array([[-0.9466428 , -1.0808687 ,  0.51816726,  0.82632685]],
      dtype=float32)>

In [ ]:
# weights for state
model.layers[1].weights[1]

<tf.Variable 'simple_rnn/simple_rnn_cell/recurrent_kernel:0' shape=(4, 4) dtype=float32, numpy=
array([[ 0.75734437,  0.08743321,  0.5753231 ,  0.29629079],
       [ 0.16652356, -0.2729957 ,  0.28726938, -0.9028951 ],
       [-0.6009762 , -0.2624599 ,  0.7279382 ,  0.2001208 ],
       [ 0.19371891, -0.9213813 , -0.23787715,  0.23862919]],
      dtype=float32)>

In [ ]:
# bias
model.layers[1].weights[2]

<tf.Variable 'simple_rnn/simple_rnn_cell/bias:0' shape=(4,) dtype=float32, numpy=array([0., 0., 0., 0.], dtype=float32)>

In [ ]:
model.fit(x, y, epochs=1000, batch_size=1, verbose=0)

In [ ]:
pred = model.predict(x, batch_size=1)
if model_type == 1:
  print(pred)
elif model_type == 2:
  print(np.round(pred, 3))
  idx = [np.argmax(r) for r in pred]
  print(idx)

[[0.002 0.004 0.001 0.993]]
[3]
