In [6]:
# setup
import numpy as np
import tensorflow as tf
from keras.models import Sequential
from keras.layers import Dense, SimpleRNNCell,SimpleRNN, RNN

### Preparing dataset

In [7]:
# One hot encoding for each char in 'hello'
h = [1, 0, 0, 0]
e = [0, 1, 0, 0]
l = [0, 0, 1, 0]
o = [0, 0, 0, 1]

In [8]:
# One cell RNN input_dim (4) -> output_dim (2)
x_data = np.array([[h]], dtype=np.float32)
print(x_data.shape)

hidden_size = 2
cell = SimpleRNNCell(units=hidden_size) # creating SimpleRNNCell
rnn = RNN(cell, return_sequences=True, return_state=True)

outputs, states = rnn(x_data)
print("파라미터 개수:", rnn.count_params())
print(rnn.weights)

print('x_data: {}, shape: {}'.format(x_data, x_data.shape))
print('outputs: {}, shape: {}'.format(outputs, outputs.shape))
print('states: {}, shape: {}'.format(states, states.shape))

(1, 1, 4)
파라미터 개수: 14
[<tf.Variable 'rnn_1/simple_rnn_cell_1/kernel:0' shape=(4, 2) dtype=float32, numpy=
array([[-0.7129483 ,  0.7383971 ],
       [-0.6790621 , -0.6630833 ],
       [-0.1064775 ,  0.39999914],
       [-0.9447224 ,  0.6135261 ]], dtype=float32)>, <tf.Variable 'rnn_1/simple_rnn_cell_1/recurrent_kernel:0' shape=(2, 2) dtype=float32, numpy=
array([[ 0.64536655, -0.7638731 ],
       [-0.7638731 , -0.6453665 ]], dtype=float32)>, <tf.Variable 'rnn_1/simple_rnn_cell_1/bias:0' shape=(2,) dtype=float32, numpy=array([0., 0.], dtype=float32)>]
x_data: [[[1. 0. 0. 0.]]], shape: (1, 1, 4)
outputs: [[[-0.61252236  0.6281758 ]]], shape: (1, 1, 2)
states: [[-0.61252236  0.6281758 ]], shape: (1, 2)


In [9]:
# equivalent to above case
rnn = SimpleRNN(units=hidden_size, return_sequences=True,
               return_state=True) # layers.SimpleRNNCell + layers.RNN

outputs, states = rnn(x_data)
print("파라미터 개수:", rnn.count_params())
print(rnn.weights)

print('x_data: {}, shape: {}'.format(x_data, x_data.shape))
print('outputs: {}, shape: {}'.format(outputs, outputs.shape))
print('states: {}, shape: {}'.format(states, states.shape))

파라미터 개수: 14
[<tf.Variable 'simple_rnn/simple_rnn_cell_2/kernel:0' shape=(4, 2) dtype=float32, numpy=
array([[ 0.79051137, -0.5826483 ],
       [-0.9017663 ,  0.0936904 ],
       [ 0.3004787 , -0.22005463],
       [-0.98254514,  0.18339205]], dtype=float32)>, <tf.Variable 'simple_rnn/simple_rnn_cell_2/recurrent_kernel:0' shape=(2, 2) dtype=float32, numpy=
array([[-0.51837516, -0.8551532 ],
       [-0.8551532 ,  0.5183753 ]], dtype=float32)>, <tf.Variable 'simple_rnn/simple_rnn_cell_2/bias:0' shape=(2,) dtype=float32, numpy=array([0., 0.], dtype=float32)>]
x_data: [[[1. 0. 0. 0.]]], shape: (1, 1, 4)
outputs: [[[ 0.6586987  -0.52458763]]], shape: (1, 1, 2)
states: [[ 0.6586987  -0.52458763]], shape: (1, 2)


In [10]:
# One cell RNN input_dim (4) -> output_dim (2). sequence: 5
x_data = np.array([[h, e, l, l, o]], dtype=np.float32)

hidden_size = 2
rnn = SimpleRNN(units=hidden_size, return_sequences=True, return_state=True)
#rnn = SimpleRNN(units=hidden_size, return_state=True, input_shape=(1, 4))
outputs, states = rnn(x_data)
print(rnn.weights)

print('x_data: {} shape: {} \n'.format(x_data, x_data.shape))
print('outputs: {} shape: {} \n'.format(outputs, outputs.shape))
print('states: {}, shape: {}'.format(states, states.shape))

[<tf.Variable 'simple_rnn_1/simple_rnn_cell_3/kernel:0' shape=(4, 2) dtype=float32, numpy=
array([[ 0.9821222 , -0.53597426],
       [-0.39870334, -0.7760565 ],
       [-0.66238713,  0.01020646],
       [ 0.6088197 , -0.56448054]], dtype=float32)>, <tf.Variable 'simple_rnn_1/simple_rnn_cell_3/recurrent_kernel:0' shape=(2, 2) dtype=float32, numpy=
array([[ 0.99848974, -0.05494075],
       [-0.05494075, -0.9984896 ]], dtype=float32)>, <tf.Variable 'simple_rnn_1/simple_rnn_cell_3/bias:0' shape=(2,) dtype=float32, numpy=array([0., 0.], dtype=float32)>]
x_data: [[[1. 0. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [0. 0. 0. 1.]]] shape: (1, 5, 4) 

outputs: [[[ 0.75398314 -0.4899346 ]
  [ 0.36362636 -0.31698012]
  [-0.27465785  0.29745924]
  [-0.74112594 -0.26521862]
  [-0.11608981 -0.253308  ]]] shape: (1, 5, 2) 

states: [[-0.11608981 -0.253308  ]], shape: (1, 2)


In [11]:
# One cell RNN input_dim (4) -> output_dim (2). sequence: 5, batch 3
# 3 batches 'hello', 'eolll', 'lleel'
x_data = np.array([[h, e, l, l, o],
                   [e, o, l, l, l],
                   [l, l, e, e, l]], dtype=np.float32)

hidden_size = 2
rnn = SimpleRNN(units=2, return_sequences=True, return_state=True)    
outputs, states = rnn(x_data)

print('x_data: {}, shape: {} \n'.format(x_data, x_data.shape))
print('outputs: {}, shape: {} \n'.format(outputs, outputs.shape))
print('states: {}, shape: {}'.format(states, states.shape))

x_data: [[[1. 0. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [0. 0. 0. 1.]]

 [[0. 1. 0. 0.]
  [0. 0. 0. 1.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]]

 [[0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [0. 1. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 1. 0.]]], shape: (3, 5, 4) 

outputs: [[[ 0.62118423  0.13709737]
  [ 0.52606964  0.90146416]
  [-0.31374252 -0.20695929]
  [ 0.7795566  -0.42581284]
  [-0.48208928  0.29230204]]

 [[ 0.75692034  0.75686115]
  [-0.91687924 -0.25076425]
  [ 0.8757411  -0.74967706]
  [ 0.75630176  0.69182295]
  [-0.23784193  0.09009311]]

 [[ 0.6152727  -0.26292697]
  [ 0.58640194  0.37850946]
  [ 0.36740142  0.8715155 ]
  [ 0.04562403  0.72605157]
  [ 0.04975189 -0.5067587 ]]], shape: (3, 5, 2) 

states: [[-0.48208928  0.29230204]
 [-0.23784193  0.09009311]
 [ 0.04975189 -0.5067587 ]], shape: (3, 2)
